django-library-management-system-master/library/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views


app_name = 'library'

urlpatterns = [
    # url(r'^index$', views.index),
    # url(r'^books$', views.books, name="books"),
    url(r'^categories$', views.categories, name="categories"),
    url(r'^returning$', views.returning, name="returning"),
    url(r'^borrow/$', views.borrow, name="borrow"),
    # url(r'^edit_book/(\d+)/$', views.edit_book, name="edit_book"),
    # url(r'^edit_category/(\d+)/$', views.edit_category, name="edit_category"),
    # url(r'^delete_book/(\d+)/$', views.delete_book, name="delete_book"),
    # url(r'^delete_category/(\d+)/$', views.delete_category, name="delete_category"),
    # path('students/', views.students, name="students"),
    path('books/', views.BookListView.as_view(), name="books"),
    path('upload/books/', views.upload_books, name='upload_books'),


]

django-library-management-system-master/libraryms/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('library.urls')),
    path('management/', include('management.urls'))
]

django-library-management-system-master/library/models.py
from datetime import date

from django.contrib.auth import get_user_model
from django.core.exceptions import FieldError
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

User = get_user_model()


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Book(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True)
    serial = models.CharField(max_length=10, blank=True, null=True, unique=True)
    categories = models.ManyToManyField(Category, blank=True)
    cover = models.TextField(max_length=100000, blank=True, null=True)
    author = models.CharField(max_length=255, null=True)
    description = models.TextField(max_length=25000, blank=True, null=True)
    available = models.IntegerField(default=0)
    price = models.CharField(max_length=50, blank=True, null=True)
    year = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    student_id = models.CharField(max_length=255, blank=True, null=True, unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    department = models.CharField(max_length=255, blank=True, null=True)
    section = models.CharField(max_length=10, blank=True, null=True)
    year = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.firstname

    @property
    def full_name(self):
        return "{} {}".format(self.firstname, self.lastname)


class Borrow(models.Model):
    book = models.ManyToManyField(Book)
    student = models.ManyToManyField(Student)
    qty = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=25)
    approved = models.BooleanField(default=False)


@receiver(pre_save, sender=Book)
def set_serial(sender, instance, *args, **kwargs):
    if not instance.id:
        last_obj = Book.objects.last()
        if last_obj:
            if last_obj.serial:
                serial = str(int(last_obj.serial) + 1).zfill(6)
                instance.serial = serial
            else:
                raise FieldError("Book object <{}>  serial does not exist".format(last_obj.id))
        else:
            instance.serial = '1'.zfill(6)
    # else:
    #     # can't update without serial if you don't want
    #     # comment out this else block
    #     if not instance.serial:
    #         raise FieldError("Book object {} does not have serial".format(instance.id))

django-library-management-system-master/library/views.py
from datetime import datetime
import os
import openpyxl
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView

# Create your views here.
from library.models import Book, Category, Student, Borrow


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    # queryset = Book.objects.filter(available__gte=1)
    queryset = Book.objects.all()
    template_name = 'library/client.html'

    def get_context_data(self, *args, **kwargs):
        obj_list = Borrow.objects.filter(student__id=self.request.user.student.id)
        context = super(BookListView, self).get_context_data(*args, **kwargs)
        borrowed_list = list()
        requested_list = list()
        for obj in obj_list.filter(status='Borrowed'):
            borrowed_book_list = list(obj.book.values_list('id', flat=True))
            borrowed_list.extend(borrowed_book_list)
            print(borrowed_list)

        for obj in obj_list.filter(status='Requested'):
            requested_book_list = list(obj.book.values_list('id', flat=True))
            requested_list.extend(requested_book_list)

        context['borrowed_list'] = borrowed_list
        print(borrowed_list)
        context['requested_list'] = requested_list
        return context


@login_required(login_url='/login')
def borrow(request):
    book_queryset = Book.objects.filter(available__gte=1)
    user_id = request.GET.get('user_id')
    book = request.GET.get('book_id')

    try:
        student_obj = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
        raise Http404("Student of id {} does not exist".format(request.user.id))
    try:
        # print("---------------", book, type(book))
        book_obj = Book.objects.get(id=int(book))

    except Book.DoesNotExist:
        raise Http404("Book Does not exist")

    status = "Requested"
    if Borrow.objects.filter(book__id=book, student__id=request.user.id):
        return redirect('/books')
    b = Borrow(qty=1, status=status)
    # print(b, "b")
    b.save()
    b.student.add(student_obj)
    b.book.add(book_obj)
    return redirect("/books/")


def index(request):
    return render(request, "index.html", {})


def categories(request):
    if request.method == "POST":
        title = request.POST['title']

        Category(title=title).save()
        return redirect('/categories')
    categories = Category.objects.all()
    return render(request, "category.html", {"categories": categories})


def delete_category(request, id):
    category = Category.objects.filter(id=id)
    category.delete()
    return redirect('/categories')


def edit_category(request, id):
    category = Category.objects.filter(id=id).get()
    return JsonResponse({'title': category.title})


def books(request):
    if request.method == "POST":
        title = request.POST['title']
        author = request.POST['author']
        cat = Category.objects.get(id=int(request.POST['category_id']))
        description = request.POST['description']
        available = int(request.POST['quantity'])

        book = Book(title=title, author=author, description=description, available=available)
        book.save()
        if book.categories.add(cat):
            return redirect('/books')
    books = Book.objects.all()
    categories = Category.objects.all()
    return render(request, "books.html", {"books": books, "categories": categories})


def edit_book(request, id):
    book = Book.objects.filter(id=id).get()
    return JsonResponse(
        {'title': book.title, 'author': book.author, 'description': book.description, 'available': book.available})


def delete_book(request, id):
    book = Book.objects.filter(id=id).get()
    book.delete()
    return redirect("/books")


# def borrow(request):
#     if request.method == "POST":
#         student_id = request.POST['student_id']
#         student = Student.objects.get(id=student_id)
#         # status = "Borrowed"
#         status = "Requested"
#         books_id = request.POST.getlist('selector')
#         for book_id in books_id:
#             book = Book.objects.get(id=book_id)
#             if Borrow.objects.filter(book__id=book_id):
#                 return redirect('/borrow')
#             b = Borrow(qty=1, status=status)
#             b.save()
#             b.student.add(student)
#             b.book.add(book)
#             return redirect("/borrow")
#     students = Student.objects.all()
#     books = Book.objects.all()
#     datas = []
#     for book in books:
#         left = Borrow.objects.filter(status="Borrowed", book__title=book.title).aggregate(Sum('qty'))
#         if left['qty__sum'] is None:
#             l = 0
#         else:
#             l = int(left['qty__sum'])
#         datas.append(book.available - l)
#     return render(request, "borrow.html", {"datas": zip(books, datas), "students": students})


def returning(request):
    if request.method == "POST":
        b_id = int(request.POST["borrow_id"])
        borrow = Borrow.objects.get(id=b_id)
        borrow.date = datetime.now()
        borrow.status = "Returned"
        borrow.save()
        return redirect('/returning')
    borrows = Borrow.objects.all()
    return render(request, "return.html", {"borrows": borrows})


def students(request):
    if request.method == "POST":
        sid = request.POST["sid"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        department = request.POST["department"]
        section = request.POST["section"]
        year = request.POST["year"]

        student = Student(student_id=sid, firstname=firstname, lastname=lastname, department=department,
                          section=section, year=year)
        student.save()
        return redirect("/students")
    students = Student.objects.all()
    return render(request, "students.html", {"students": students})


def upload_books(request):
    cwd = os.getcwd()
    myfile = os.path.join(cwd, "book.XLSX")
    wb = openpyxl.load_workbook(myfile)
    for sheet in wb.get_sheet_names():
        cur_sheet = wb.get_sheet_by_name(sheet)
        for cell in cur_sheet.values:
            print(cell)
            book = Book.objects.create(title=cell[2], author=cell[3], year=cell[5], price=cell[6])
            category = cell[4]

            if category:
                if not Category.objects.filter(title=cell[4]):
                    category = Category.objects.create(title=category)
                else:
                    category = Category.objects.filter(title=category).first()
                book.categories.add(category)
    return HttpResponse("Hi")

django-library-management-system-master/library/templates/library/client.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Library</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

</head>
<body style="background: #1AC8DB; background-size: cover;">

<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand">Indian Oil Corporation</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">{{request.user.student.firstname}}</a>
        </li>
    </ul>
    <form class="form-inline">
        <input class="form-control mr-sm-2 light-table-filter" data-table="order-table" type="search"
               placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

</nav>
<div class="container" style="background: rgba(0,0,0,0);">
    <br>
    <br>
    <h3>Library Books:</h3>
    <table class="table table-dark order-table">
        <thead>
        <tr>
            <th scope="col">Sl No.</th>
            <th scope="col">Name of Book</th>
            <th scope="col">Author</th>
            <th scope="col">Category</th>
            <th scope="col">Available</th>
            <th scope="col">Request</th>

        </tr>
        </thead>
        <tbody>
        {% for book in book_list %}

        <tr>
            <th scope="row">{{book.serial}}</th>
            <th scope="row">{{book.title}}</th>
            <th scope="row">{{book.author}}</th>
            <th scope="row">
                {% for category in book.categories.all %}
                    {{category}}&nbsp;
                {% endfor %}
            </th>
            <th scope="row">{{book.available}}</th>
            <th scope="row">

                    {% if book.id in requested_list %}
                        <a href="/borrow/?user_id={{request.user.id}}&book_id={{book.id}}">
                            <button disabled type="button" class="btn btn-info btn-sm">Requested</button>
                        </a>

                    {% elif book.id in borrowed_list %}
                        <a href="/borrow/?user_id={{request.user.id}}&book_id={{book.id}}">
                            <button disabled type="button" class="btn btn-primary btn-sm">Borrowed</button>
                        </a>
                    {% else %}
                        <a href="/borrow/?user_id={{request.user.id}}&book_id={{book.id}}">
                            <button type="button" class="btn btn-success btn-sm">Request</button>
                        </a>
                    {% endif %}

            </th>


        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
<script type="text/javascript">
  (function(document) {
'use strict';

var LightTableFilter = (function(Arr) {

  var _input;

  function _onInputEvent(e) {
    _input = e.target;
    var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
    Arr.forEach.call(tables, function(table) {
      Arr.forEach.call(table.tBodies, function(tbody) {
        Arr.forEach.call(tbody.rows, _filter);
      });
    });
  }

  function _filter(row) {
    var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
    row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
  }

  return {
    init: function() {
      var inputs = document.getElementsByClassName('light-table-filter');
      Arr.forEach.call(inputs, function(input) {
        input.oninput = _onInputEvent;
      });
    }
  };
})(Array.prototype);

document.addEventListener('readystatechange', function() {
  if (document.readyState === 'complete') {
    LightTableFilter.init();
  }
});

})(document);



</script>

</body>
</html>