django-library-management-system-master/library/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views


app_name = 'library'

urlpatterns = [
    # url(r'^index$', views.index),
    # url(r'^books$', views.books, name="books"),
    url(r'^categories$', views.categories, name="categories"),
    url(r'^returning$', views.returning, name="returning"),
    url(r'^borrow/$', views.borrow, name="borrow"),
    # url(r'^edit_book/(\d+)/$', views.edit_book, name="edit_book"),
    # url(r'^edit_category/(\d+)/$', views.edit_category, name="edit_category"),
    # url(r'^delete_book/(\d+)/$', views.delete_book, name="delete_book"),
    # url(r'^delete_category/(\d+)/$', views.delete_category, name="delete_category"),
    # path('students/', views.students, name="students"),
    path('books/', views.BookListView.as_view(), name="books"),
    path('upload/books/', views.upload_books, name='upload_books'),


]

django-library-management-system-master/libraryms/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('library.urls')),
    path('management/', include('management.urls'))
]

django-library-management-system-master/management/urls.py
from django.urls import path
from .views import RequestedBooks, approve, returning, students, reject

#

app_name = 'management'
urlpatterns = [
    path('requested-books/', RequestedBooks.as_view(), name='requested_books'),
    path('approve/', approve, name='approve_book'),
    path('reject/', reject, name='reject_book'),
    path('return/', returning, name='return_book'),
    path('students/', students, name="students"),

]

django-library-management-system-master/library/models.py
from datetime import date

from django.contrib.auth import get_user_model
from django.core.exceptions import FieldError
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

User = get_user_model()


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Book(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True)
    serial = models.CharField(max_length=10, blank=True, null=True, unique=True)
    categories = models.ManyToManyField(Category, blank=True)
    cover = models.TextField(max_length=100000, blank=True, null=True)
    author = models.CharField(max_length=255, null=True)
    description = models.TextField(max_length=25000, blank=True, null=True)
    available = models.IntegerField(default=0)
    price = models.CharField(max_length=50, blank=True, null=True)
    year = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    student_id = models.CharField(max_length=255, blank=True, null=True, unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    department = models.CharField(max_length=255, blank=True, null=True)
    section = models.CharField(max_length=10, blank=True, null=True)
    year = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.firstname

    @property
    def full_name(self):
        return "{} {}".format(self.firstname, self.lastname)


class Borrow(models.Model):
    book = models.ManyToManyField(Book)
    student = models.ManyToManyField(Student)
    qty = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=25)
    approved = models.BooleanField(default=False)


@receiver(pre_save, sender=Book)
def set_serial(sender, instance, *args, **kwargs):
    if not instance.id:
        last_obj = Book.objects.last()
        if last_obj:
            if last_obj.serial:
                serial = str(int(last_obj.serial) + 1).zfill(6)
                instance.serial = serial
            else:
                raise FieldError("Book object <{}>  serial does not exist".format(last_obj.id))
        else:
            instance.serial = '1'.zfill(6)
    # else:
    #     # can't update without serial if you don't want
    #     # comment out this else block
    #     if not instance.serial:
    #         raise FieldError("Book object {} does not have serial".format(instance.id))

django-library-management-system-master/management/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    employee_id = models.CharField(max_length=20, blank=False, null=True)

django-library-management-system-master/management/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View

from library.models import Book, Borrow, Student


# Create your views here.


class RequestedBooks(LoginRequiredMixin, View):
    def get(self, request):
        if not request.user.is_staff:
            return redirect('/books')
        requested_list = Borrow.objects.filter(status='Requested')
        borrowed_list = Borrow.objects.filter(status='Borrowed')
        return render(request, 'management/backup.html',
                      context={'requested_list': requested_list, 'borrowed_list': borrowed_list})


@login_required(login_url='/login')
def approve(request):
    if not request.user.is_staff:
        return redirect('/books')
    student_id = request.GET.get('student')
    book_id = request.GET.get('book')
    borrow_id = request.GET.get('borrow')
    # student_obj = Student.objects.get(id=student_id)
    student_obj = get_object_or_404(Student, id=student_id)
    book_obj = get_object_or_404(Book, id=book_id)
    borrow_obj = get_object_or_404(Borrow, id=borrow_id)
    book_obj.available -= 1
    book_obj.serial = book_obj.serial
    book_obj.save()
    borrow_obj.status = 'Borrowed'
    borrow_obj.approved = True
    borrow_obj.save()
    return redirect('management:requested_books')


def reject(request):
    if not request.user.is_staff:
        return redirect('/books')
    # student_id = int(request.GET.get('student'))
    book_id = int(request.GET.get('book'))
    borrow_id = int(request.GET.get('borrow'))
    borrow_obj = get_object_or_404(Borrow, id=borrow_id)
    # student_obj = get_object_or_404(Student, id=student_id)
    book_obj = get_object_or_404(Book, id=book_id)
    borrow_obj.book.remove(book_obj)
    return redirect('management:requested_books')


def returning(request):
    if request.user.is_staff:
        b_id = int(request.GET.get("borrow_id"))
        book_id = int(request.GET.get('book'))
        borrow = get_object_or_404(Borrow, id=b_id)
        book = get_object_or_404(Book, id=book_id)
        book.available = book.available + 1
        book.save()
        borrow.date = datetime.now()
        borrow.status = "Returned"
        borrow.save()
        return redirect('management:requested_books')
    return redirect('/books')


@login_required(login_url='/login')
def students(request):
    if not request.user.is_staff:
        return redirect('/books')
    if request.method == "POST":
        sid = request.POST["sid"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        department = request.POST["department"]
        section = request.POST["section"]
        year = request.POST["year"]

        student = Student(student_id=sid, firstname=firstname, lastname=lastname, department=department,
                          section=section, year=year)
        student.save()
        return redirect("/students")
    students = Student.objects.all()
    return render(request, "students.html", {"students": students})

django-library-management-system-master/management/templates/management/backup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    {% load static %}

    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

</head>
<body style="background-color:#0bb5e1">
{% load management_tag %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Indian Oil Corporation</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>
<br>
<br>

<div class="container">
    <h3>Requested Books:</h3>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">Sl. No</th>
            <th scope="col">Name of Book</th>
            <th scope="col">Author</th>
            <th scope="col">Requested By</th>
            <th scope="col">Choose</th>
        </tr>
        </thead>
        <tbody>
            {% for borrow in requested_list %}
                {% for book in borrow.book.all %}
                    {% for student in borrow.student.all %}
            <tr>
                        <td scope="row"> {{book.serial}}
                        </td>
                        <td scope="row">{{book}}</td>
                        <td scope="row"> {{book.author}}</td>
                        <td scope="row">{{student.firstname}} {{student.lastname}}</td>
                        <td scope="row">
                            <a href="/management/approve/?student={{student.id}}&book={{book.id}}&borrow={{borrow.id}}">
                                <button type="button" class="btn btn-success">Accept</button>
                            </a></td>
                        <td><a href="/management/reject/?student={{student.id}}&book={{book.id}}&borrow={{borrow.id}}">
                            <button type="button" class="btn btn-danger">Reject</button>
                        </a></td>
                        </td>
            </tr>
                    {% endfor %}
                {% endfor %}

            {% endfor %}
        </tr>
        </tbody>
    </table>
</div>

<br>
<br>

<div class="container">
    <h3>Issued Books:</h3>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">Sl. No</th>
            <th scope="col">Name of Book</th>
            <th scope="col">Author</th>
            <th scope="col">Issued To</th>
            <th scope="col">Choose</th>
        </tr>
        </thead>
        <tbody>
            {% for borrow in borrowed_list %}
            {% for book in borrow.book.all %}
            {% for student in borrow.student.all %}
            <tr>
            <td scope="row"> {{book.serial}}
            </td>
            <td scope="row">{{book}}</td>
            <td scope="row"> {{book.author}} {{student.lastname}}</td>
            <td scope="row">{{student.firstname}} {{student.lastname}}</td>
            <td scope="row">
                <a href="/management/return/?borrow_id={{borrow.id}}&book={{book.id}}&borrow={{borrow.id}}">
                    <button type="button" class="btn btn-success">Return</button>
                </a>
            </td>
            </tr>

            {% endfor %}
            {% endfor %}
            {% endfor %}
        </tr>

        </tbody>
    </table>
</div>
</body>
</html>

django-library-management-system-master/management/templates/management/new.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
z
</head>
<body style="background-color:#0bb5e1">


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Indian Oil Corporation</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>
<br>
<br>

<div class="container">
    <h3>Requested Books:</h3>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">Sl. No</th>
            <th scope="col">Name of Book</th>
            <th scope="col">Author</th>
            <th scope="col">Requested By</th>
            <th scope="col">Choose</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for borrow in borrow_list %}
            {% for book in borrow.book.all %}
            {% for student in borrow.student.all %}
            <td scope="row"> {{book.id}}
            </td>
            <td scope="row">{{book}}</td>
            <td scope="row"> {{student.firstname}} {{student.lastname}}</td>
            <td scope="row">{{borrow.status}}</td>
            <td scope="row">
                <a href="/management/approve/?student={{student.id}}&book={{book.id}}&borrow={{borrow.id}}">
                    <button type="button" class="btn btn-success">Accept</button>
                </a>
                <button type="button" class="btn btn-danger">Reject</button>
            </td>

            {% endfor %}
            {% endfor %}
            {% endfor %}

        </tr>
        </tbody>
    </table>
</div>

<br>
<br>

<div class="container">
    <h3>Issued Books:</h3>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">Sl. No</th>
            <th scope="col">Name of Book</th>
            <th scope="col">Author</th>
            <th scope="col">Issued To</th>
            <th scope="col">Choose</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for borrow in requested_list %}
            {% for book in borrow.book.all %}
            {% for student in borrow.student.all %}
            <td scope="row"> {{book.id}}
            </td>
            <td scope="row">{{book}}</td>
            <td scope="row"> {{student.firstname}} {{student.lastname}}</td>
            <td scope="row">{{borrow.status}}</td>
            <td scope="row">
                <a href="/management/approve/?student={{student.id}}&book={{book.id}}&borrow={{borrow.id}}">
                    <button type="button" class="btn btn-success">Accept</button>
                </a>
                <button type="button" class="btn btn-danger">Reject</button>
            </td>
            {% endfor %}
            {% endfor %}
            {% endfor %}
        </tr>

        </tbody>
    </table>
</div>

</body>

django-library-management-system-master/management/templates/management/old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADMIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <table style="width:100%">
        <tr>
            <th>Book</th>
            <th>Requested By</th>
            <th>status</th>
            <th></th>
        </tr>
    <tr>
        {% for borrow in requested_list %}
        {% for book in borrow.book.all %}
        {% for student in borrow.student.all %}
        <td>{{book}}</td>
        <td> {{student.firstname}} {{student.lastname}}</td>
        <td>{{borrow.status}}</td>

        {% endfor %}
        {% endfor %}
        {% endfor %}
</tr>
    </table>
</div>

        {% for borrow in requested_list %}
            {{borrow}} {{requested_list}}
        {% endfor %}
</body>
</html>

django-library-management-system-master/management/templates/management/requested_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADMIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <table style="width:100%">
        <tr>
            <th>Book</th>
            <th>Requested By</th>
            <th>status</th>
            <th></th>
        </tr>

        {% for borrow in borrow_list %}
        {% for book in borrow.book.all %}
        {% for student in borrow.student.all %}
        <td>{{book}}</td>
        <td> {{student.firstname}} {{student.lastname}}</td>
        <td>{{borrow.status}}</td>
        <td>
            <form method="get" action="/management/approve/">
                <input type="hidden" name="student" value={{student.id}}><input>
                <input type="hidden"  name="book" value={{book.id}} ><input>
                <input type="hidden" name="borrow" value={{borrow.id}}><input>
                <button class="btn btn-success" type="submit">Approve</button>
            </form>
        </td>
        {% endfor %}
        {% endfor %}
        {% endfor %}

    </table>
</div>

</body>
</html>